import GoogleMapsApiLoader from '@/google-maps-api-loader';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='mt-20 mx-auto px-5 sm:max-w-md md:max-w-xl xl:max-w-3xl'>
        <GoogleMapsApiLoader>{children}</GoogleMapsApiLoader>
      </body>
    </html>
  );
}
