import GoogleMapsApiLoader from '@/google-maps-api-loader';
import './globals.css';
import type { Metadata } from 'next';
import { Lora } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const lora = Lora({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={lora.className}>
      <body className='mt-20 mx-auto px-5 sm:max-w-xl xl:max-w-3xl'>
        <GoogleMapsApiLoader>{children}</GoogleMapsApiLoader>
      </body>
    </html>
  );
}
